### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tcoyze** [patrickml/pokelert#8]
I am having issues with the installation process of your project on my machine (Mac OSX 10.11.6):
I ran the following:

`$ git clone git@github.com:patrickml/pokelert.git`
`$ cd pokelert`
`$ npm install`
According to react-native-maps:
`$ rnpm link`
Then finally:
`$ react-native run-ios`

However the build keeps failing with:

```
Unable to run command 'Libtool libAirMaps.a' - this target might include its own product

(... a little further down...)

The following build commands failed:
    Check dependencies
(1 failure)
/Users/tyler/Projects/pokelert/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

```

**Comment by patrickml** [comment]
Interesting... Give me a few minutes to check something out.

**Comment by tcoyze** [comment]
Thanks! I'm stoked to start playing around with this on my phone. I just started using react-native so I thought this looked like a cool project to learn from.

**Comment by patrickml** [comment]
Yeh man let me know if you have any questions once we get you up and
running.

**Comment by patrickml** [comment]
I think the issue has to do with ReactNativeMaps https://github.com/lelandrichardson/react-native-maps/issues/371 I had fixed the issue, but it's possible it needs to be fixed locally on each computer. I'll keep looking.

**Comment by tcoyze** [comment]
No worries. After some more digging by building in xcode, it seems that header files referenced in AirMap cannot be found.

Example:

`AirmapCallout.h cannot find React/RCTView.h`

**Comment by tcoyze** [comment]
Thanks I'll take a look!

**Comment by patrickml** [comment]
@tcoyze Yup that was the issue. I'm not sure how to include the fix in the build since it comes from a dependency.

**Comment by patrickml** [comment]
Oh also don't forget to checkout the development branch its further ahead

**Comment by tcoyze** [comment]
OK, I got it working! That was the issue!

**Comment by patrickml** [comment]
@tcoyze great man! Would love to get some PR's if you have time!
